### ISSUE TITLE
MIT

### ISSUE THREAD

**Issue by liangjl76** [SharpKit/SharpKit#19] opened 2016-06-21 08:01 UTC
Watch and use of people too little, it is better to change the open source protocol to MIT

**Comment by mylemans** [comment] 2016-11-09 04:32
I think the license is just fine. Keep in mind that the referenced DLLs and JS files are LGPL licensed.

Also, it is not because that the compiler is GPL that generated output (the javascript) is GPL! 

Look at GIMP: It is also GPL, but that does not mean that the images that you created with it fall under the GPL!

So in short: The SharpKit GPL license is no problem for using it in closed source / commercial applications as the files that you reference (dll / core js libraries) are not GPL (they're LGPL) and the generated JS code doesn't even have any specific license attached to it.

In addition, it is too late to switch now or the maintainer will need to get an OK from everyone who ever aided with the project. The curse of GPL.. :P

**Comment by hultqvist** [comment] 2016-11-09 07:47
I totally agree with @mylemans.

The problem is that the authors give mixed messages. On the one hand it is under the GPL/LGPL, on the other hand the README and the website says that for commercial use you must buy a license.

The "problem" with low usage might be more that it's a niche market, C# people who want to write JavaScript.

**Comment by danelkhen** [comment] 2016-11-09 07:52
Hey guys, license it updated to MIT now on github

**Comment by geoffreymcgill** [comment] 2017-02-01 15:10
Apache 2.0 is a better choice. MIT is fine, and simple, but the Apache has a specific Patent assignment, so much better for end users.

The copyright holder can change the license whenever they please, but a license change is not retro active. If you acquired the library under a GPL/LGPL license, then that instance of the license stays with your code. The code is not automatically superseded if the license changes further downstream.

@danelkhen – excellent choice moving to a more permissive open-source license. 👍 ⭐️

**Comment by mylemans** [comment] 2017-02-01 16:25
I'm happy with the choice for MIT

**Comment by Arakis** [comment] 2018-06-10 09:55
Issue solved on Nov 9, 2016

**Closed by Arakis** 2018-06-10 09:55 UTC
